### ISSUE TITLE
DEI organization

### ISSUE THREAD

**Issue by xmnlab** [OpenScienceLabs/opensciencelabs.github.io-archive#13]
Create a workgroup for DEI topics. 

Ref:

- https://opensourcediversity.org/
- https://frameshiftconsulting.com/code-of-conduct-book/

**Comment by petrizzo** [comment]
Saludos. Este grupo es el de Discord o deberíamos también agregar más detalles a la carpeta incluida aquí en /docs?

**Comment by xmnlab** [comment]
se trata de un grupo de personas, como un comité .. podemos usar el canal collab-dei en discord para el comité

**Comment by petrizzo** [comment]
ok. Entendido. Entonces el issue que acabo de crear viene ideal para ese grupo.

**Comment by xmnlab** [comment]
voy a cerrar esta issue. cuando tengamos un grupo de DEI podemos abrirla otra vez.
