### ISSUE TITLE
Domain configuration is reset every build

### ISSUE THREAD

**Issue by esloch** [OpenScienceLabs/opensciencelabs.github.io-archive#31]
#### Problem
When the GitHub action builds a new version and pushes it to the gh-pages branch, the custom domain setting in the GitHub settings gets reset.
#### Posible solution
- [x]  Crear en main una carpeta para files
- [x] Mover el CNAME del root para files
- [x] Chequear si tenemos FILES_FOLDERS en el archivo conf.py

**Comment by xmnlab** [comment]
not sure if it is useful yet: https://github.com/getnikola/nikola-action

**Comment by esloch** [comment]
> not sure if it is useful yet: https://github.com/getnikola/nikola-action

Would we remove the **miniconda@v2**?

**Comment by xmnlab** [comment]
Maybe we could keep both ... but for now we can wait about this ghactions, maybe it will not improve our workflow
