### ISSUE TITLE
Update team's page

### ISSUE THREAD

**Issue by xmnlab** [OpenScienceLabs/opensciencelabs.github.io-archive#40]
The Team's page needs to be updated: https://opensciencelabs.org/team/

# Board

The current board is Ever, Eunice and Ivan

# Collaborators

Add Petrizzo, Francisco, Ingrid, Sandro, Yurely, Anavelyz and Jasmeet

**Comment by xmnlab** [comment]
the file to be changed is: https://github.com/OpenScienceLabs/opensciencelabs.github.io/blob/main/pages/team.html

**Comment by xmnlab** [comment]
@YurelyCamacho could take a look into that pls?

cc @EverVino

**Comment by YurelyCamacho** [comment]
Hola, ya lo hago.

**Comment by xmnlab** [comment]
thanks for working on that @YurelyCamacho !
PS: next time in the first comment inside your PR please mention which issue you are resolving and this issue will be closed automatically: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

here in this table (from the link above), you can see an example about how to do that:

Linked issue | Syntax | Example
-- | -- | --
Issue in the same repository | KEYWORD #ISSUE-NUMBER | Closes #10
Issue in a different repository | KEYWORD OWNER/REPOSITORY#ISSUE-NUMBER | Fixes octo-org/octo-repo#100
Multiple issues | Use full syntax for each issue | Resolves #10, resolves #123, resolves octo-org/octo-repo#100
