### ISSUE TITLE
Add pyOpenSci as a partner

### ISSUE THREAD

**Issue by xmnlab** [OpenScienceLabs/opensciencelabs.github.io-archive#44]
Add pyOpenSci as a partner.

webpage: https://www.pyopensci.org/
github: https://github.com/pyOpenSci/software-review
twitter: https://twitter.com/pyopensci

PS: font-awesome for twitter: https://fontawesome.com/v5/icons/twitter?s=brands

**Comment by luabida** [comment]
for some reason the font-awesome doesn't work this way in OSL webserver, the correct way is using 
`<i class="fa fa-brands fa-[...]>`
