### ISSUE TITLE
Article: Create an article about Apache Superset

### ISSUE THREAD

**Issue by xmnlab** [OpenScienceLabs/opensciencelabs.github.io-archive#50]

**Comment by xmnlab** [comment]
@YurelyCamacho could you work on this one? I think that it would be nice because it will be a link to epigraphhub

**Comment by xmnlab** [comment]
if we could have this in 1 month ready for review, that would be great. so, no rush :)

**Comment by YurelyCamacho** [comment]
@xmnlab No conozco sobre el tema, pero con gusto lo haré.

**Comment by YurelyCamacho** [comment]
Si tienen algunas referencias son bienvenidas.

**Comment by xmnlab** [comment]
https://superset.apache.org/docs/creating-charts-dashboards/creating-your-first-dashboard/

epigraphhub.org es basicamente el apache superset .. puedes usarlo para tu artículo
