### ISSUE TITLE
GRANT: Check posibles institutions for applying for a grant

### ISSUE THREAD

**Issue by xmnlab** [OpenScienceLabs/opensciencelabs.github.io-archive#53]
Create a list with 5 possibles institutions for applying for grant. Add details information about how to apply and requirements.

Add these information to the fund raising doc section.

cc @EverVino

**Comment by EverVino** [comment]
Podrían darle un vistazo a esto
https://www.python.org/psf/grants/

**Comment by YurelyCamacho** [comment]
Gracias, @EverVino

**Comment by xmnlab** [comment]
PR merged. thanks @YurelyCamacho
