### ISSUE TITLE
Investigate how we can apply to be part of Google Summer Of Code

### ISSUE THREAD

**Issue by xmnlab** [OpenScienceLabs/opensciencelabs.github.io-archive#62]
ref:
- https://summerofcode.withgoogle.com/rules - see point 4

cc @EverVino

**Comment by Anavelyz** [comment]
@xmnlab @EverVino ¿Dónde almaceno la información recopilada?

**Comment by xmnlab** [comment]
Puede ser en mentoring por el momento.

**Comment by xmnlab** [comment]
#88 merged. thanks @Anavelyz
