### ISSUE TITLE
Create tweets about the new recording of our pycafe meetings

### ISSUE THREAD

**Issue by xmnlab** [OpenScienceLabs/opensciencelabs.github.io-archive#71]
publish one tweet per video to publicize each record of our pycafe talks (one tweet per video).

list of videos: https://www.youtube.com/watch?v=lPsOB8dEiNI&list=PLO9FcAjX-qxgtjWs4QxlDylVoPoFy5opU 

cc @eunrod16

**Comment by eunrod16** [comment]
@Gretzel Puedes seguir el siguiente formato con cada uno de los tweets de pycafe, de igual manera te envío el editable cualquier cosa me cuentas https://www.canva.com/design/DAFI4Jkz034/hjhWWmNI0S7pWZsJFNqY5g/edit?utm_content=DAFI4Jkz034&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by eunrod16** [comment]
No te olvides de nuestro próximo evento el 12 de agosto en el siguiente link: https://www.eventbrite.com/e/osl-python-cafe-latinoamerica-tickets-398916358567?aff=erelexpmlt
Puedes ver la charla completa de Rafael aquí https://www.youtube.com/watch?v=lPsOB8dEiNI&list=PLO9FcAjX-qxgtjWs4QxlDylVoPoFy5opU&ab_channel=OpenScienceLabs
![OSL Tweet Post](https://user-images.githubusercontent.com/12076074/183782503-a23dbb5a-e010-4a8c-a5a6-9c22b27cb251.png)

**Comment by xmnlab** [comment]
he cambiado el thumbnail de la charla aquí: https://www.youtube.com/playlist?list=PLO9FcAjX-qxgtjWs4QxlDylVoPoFy5opU
se ve genial @eunrod16, muchas gracias! you rock!

@Gretzel cuando puedas hacer de las otras charlas, yo puedo actualizar en youtube

**Comment by xmnlab** [comment]
creo que todo ya está en camino. voy a cerrar esta issue por el momento.
en el caso de que algo esté faltando. lo reabrimos otra vez :)
